[paths]
workspace = "apps/backend"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --no-audit"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc"
]

[start]
cmd = "node dist/index.js"
